@to-do-mini-api_HostAddress = http://localhost:5202
//Obs: alterar os ids de tema e autor para qualquer um que for gerado ao fazer as requisições de post em usuários e em temas

//Requisição POST de Usuário
POST {{to-do-mini-api_HostAddress}}/baixium/usuarios
Content-Type: application/json

{
  "nome": "Abner Benicio",
  "email": "abnerbeniciosilva123@gmail.com",
  "password": "1203",
  "administrador":true
}

###

//Requisição POST de Artigo
POST {{to-do-mini-api_HostAddress}}/baixium/artigos
Content-Type: application/json

{
  "titulo":"walk cat",
  "conteudo":"walk@gmail.com",
  "validado":true,
  "autor": {
    "id": "1661095a-e2bd-4a7c-fbae-08dc7fe79d9a",
    "nome": "abner benicio",
    "email": "abner@gmail.com",
    "password": "123",
    "administrador": true
  },
  "tema": {
    "id": "24b45fb2-01bd-4dda-d267-08dc7ff43093",
    "tipo": "programacao",
    "titulo": "Programação"
  }
}

###

//Requsição POST de Tema
POST {{to-do-mini-api_HostAddress}}/baixium/temas
Content-Type: application/json

{
  "tipo":"programacao",
  "titulo":"Programação"
}

###

//Requisição GET de Usuários
GET {{to-do-mini-api_HostAddress}}/baixium/usuarios

###
